FROM serverwentdown/env:alpine-node

COPY . /usr/local/share/file-manager
RUN cd /usr/local/share/file-manager \
	&& sudo npm install .

USER ambrose

ENV SHELL="zsh -l"
ENV NODE_ENV=production

CMD ["node", "/usr/local/share/file-manager/index.js"]
