FROM registry.labs.0x.no/env

USER root

RUN apk add --no-cache \
    build-base \
    python2

COPY . /usr/local/fm

RUN cd /usr/local/fm \
    && yarn install \
    && yarn cache clean
    
USER ambrose

CMD ["node", "/usr/local/fm/index.js"]
